<?php
/**
 * @file
 * The primary PHP file for this theme.
 */

function jewelrycandles_commerce_product_view_alter(&$build, $type) {
  $product = $build['#entity'];
  $product_wrapper = entity_metadata_wrapper('commerce_product', $product);
  if ( !empty($product_wrapper) ) {
    $collections = $product_wrapper->field_collection->value();
    if ( !empty($collections[0]) ) {
      // Determine the collection
      $collection = $collections[0];
      $collection_name = drupal_clean_css_identifier(strtolower($collection->name));
      $build['collections'] = $collection;
      
      // Build the url
      $link = 'collections/' . $collection_name . '/' . $product->sku;
      
      // Update the Image
      $build['field_product_image'][0]['#path']['path'] = $link;
      unset($build['field_product_image'][0]['#path']['#options']);
      
      // Update the Title
      $build['title']['#markup'] = sprintf('<div class="commerce-product-title">%s</div>', l($product->title, $link));
    }
  }
}

/* 
 * Creates the additional elements for the Feature Set system
 * The html structure for this is automagically generated by drupal and not by this theme.
 * This theme instead uses CSS to create the complex layout.
 */
function jewelrycandles_field_collection_item_view_alter(&$build, $type) {
  
  if ( $build['#bundle'] == 'field_feature_sets') {
    
    $path = $build['field_feature_set_link'][0]['#markup'];
    unset($build['field_feature_set_link']);
    
    // Link the Feature Set Image
    $build['field_feature_set_image'][0]['#path']['path'] = $path;
    
    // Link the Description Box (Which overlaps the image)
    $description_link = l('<div class="text">' . $build['field_feature_set_description'][0]['#markup'] . '</div>', $path, array(
      'html' => true, 
    ));
    
    $build['field_feature_set_description'][0]['#markup'] = $description_link;
    
    $view_more_link = l('View More <span class="glyphicon glyphicon-chevron-right"></span>', $path, array(
      'html' => true, 
      'attributes' => array(
        'class' => array('btn', 'btn-primary', 'view-more-button'),
      )
    ));
    
    $view_all_link = l('View All ' . $build['field_feature_set_title'][0]['#markup'] . ' <span class="glyphicon glyphicon-chevron-right pull-right"></span>', $path, array(
      'html' => true, 
      'attributes' => array(
        'class' => array('btn', 'btn-info', 'view-all-button'),
      )
    ));
    
    
    $build['view_more'] = array(
      '#markup' => $view_more_link,
      '#weight' => 4,
      '#access' => true,
    );
    
    $build['view_all'] = array(
      '#markup' => '<div class="view-all-button-wrapper">' . $view_all_link . '</div>',
      '#weight' => 4,
      '#access' => true,
    );
  }
}
//
//function jewelrycandles_preprocess_html(&$vars) {
//  if ( !empty($_COOKIE['Drupal_simpletoolbar_expanded']) ) {
//    $vars['classes_array'][] = 'toolbar-expanded';
//  }
//}

function jewelrycandles_preprocess_page(&$vars) {
  if(isset($vars['page']['content']['system_main']['no_content'])) {
    unset($vars['page']['content']['system_main']['no_content']);
  }
}






function jewelrycandles2_commerce_product_bundle_attribute($variables) {
  $sub_line_item = $variables['sub_line_item'];
  $product_attribute_view = $variables['product_attribute_view'];

  if (!empty($product_attribute_view)) {
    $product_attribute_view = '<div class="commerce-product-bundle-product-attributes">' . $product_attribute_view . '</div>';
  }

  

  //$output .= '<span class="commerce-product-bundle-quantity">' . (float) $sub_line_item->quantity . '</span>';
  //$output .= ' xxxx ';
  
  
  $sub_line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $sub_line_item);
  $sub_product = $sub_line_item_wrapper->commerce_product->value();
  $parent_line_item = $sub_line_item_wrapper->commerce_parent_line_item->value();
  if ( !empty($parent_line_item->commerce_product ) ) {
    
    $parent_line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $parent_line_item);
    $parent_product = $parent_line_item_wrapper->commerce_product->value();
    
    if ( $sub_product->type == 'product' ) {
      $target_field = 'field_select_your_scent';
      $target_label = 'Selected Scent:';
    } elseif ( $sub_product->type == 'jewel' ) {
      $target_field = 'field_select_your_jewelry';
      $target_label = 'Selected Jewelry:';
    } else {
      $output = '<div class="commerce-product-bundle-sub-line-item"><div class="commerce-product-bundle-sub-line-item-title">';
      $output .= '<span class="commerce-product-bundle-title">' . commerce_line_item_title($sub_line_item) . '</span></div>';
      $output .= $product_attribute_view;
      $output .= '</div>';
      return $output;
    }
    
    if ( !empty($target_field) && !empty($parent_product->{$target_field}['und']) && count($parent_product->{$target_field}['und']) > 1) {
      $output = '<div class="commerce-product-bundle-sub-line-item"><div class="commerce-product-bundle-sub-line-item-title">';
      $output .= '<span>' . $target_label . '</span> ';
      $output .= '<span class="commerce-product-bundle-title">' . commerce_line_item_title($sub_line_item) . '</span></div>';
      $output .= $product_attribute_view;
      $output .= '</div>';
      return $output;
    }
  }
  
  return '';
  
  

  
}



